### ISSUE TITLE
Make Index Configurable

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-index-files#2]
Maybe something like this:

```javascript
module.exports = {
    fulltext: {
        source: 'md',
        select: 'paragraph, header',
        properties: {
            value: 'string', // try to read the string property on the node, else call the string function on the node
            type: "'foobar'" // use the plain value 'foobar' (without the quotes)
        }
    },
    images: {
        source: 'html', // fetch the rendered page, pipe it into JSDOM
        fetch: 'https://mydomain.com/{path}.html',
        select: 'img',
        properties: {
            url: 'src',
            value: 'alt'
        }
    }

}
```

We need to figure how to load the config.

**Comment by dominique-pfister** [comment]
Current proposal:
```
#
# index configuration for theblog (hackathon vii)
#
version: 1

indices:
  blog-posts:
    source: html
    fetch: https://helix-norddal-anfibiacreativa.project-helix.page/{path}
    properties:
      author:
        select: .blog-author p a
        value: "{textContent}"
        faceted: true
      title:
        select: h1:first-of-type
        value: "{textContent}"
        faceted: true
      date:
        select: ".blog-author p:nth-child(2)"
        value: "{parseTimestamp(\"[POSTED ON] MM-DD-YYYY\")}"
      topics:
        select: .blog-topics.default > ul > li
        value: "{textContent}"
        faceted: true
      hero:
        select: main > div > img:first-of-type
        value: "{src}"
```

**Comment by dominique-pfister** [comment]
Current proposal changed again:
```
version: 1
​
indices:
  blog-posts:
    source: html
    fetch: https://{repo}-{owner}.project-helix.page/{path}
    properties:
      author:
        select: main > div:nth-of-type(3) > p:nth-of-type(1)
        value: |
          match(el, 'by (.*)')
        faceted: true
      title:
        select: h1:first-of-type
        value: |
          textContent(el)
      date:
        select: main > div:nth-of-type(3)
        value: |
          parseTimestamp(el, '[POSTED ON] MM-DD-YYYY')
      topics:
        select: main > div:last-of-type > p:first-of-type
        values: |
          match(el, '(Topics: )? ([^,]+)')
        faceted: true
      products:
        select: main > div:last-of-type > p:nth-of-type(2)
        values: |
          match(el, '(Products: )? ([^,]+)')
        faceted: true
      hero:
        select: main > div:nth-of-type(2) img:first-of-type
        value: |
          attribute(el, 'src')
      teaser:
        select: main > div:nth-child(n+4) p
        value: |
          words(textContent(el), 0, 20)
      sourceHash:
        select: head > meta[name=x-source-hash
        value: |
          attribute(el, 'content')
        faceted: true
```
