### ISSUE TITLE
Define indexing domain in helix-query.yaml

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-index-files#89]
For external change notifications (such as those posted by `helix-onedrive-listener`), it is necessary to define a `domain` of changes that should actually trigger an indexing operation, e.g. all entries in `ms/posts/2018` or `ms/posts/2019` but not `ms/posts/2017` or `ms/drafts`.

Suggest to add a new entry in `helix-query.yaml`, called `domain`, that contains a `regex`:
```
indices:
  blog-posts:
    source: html
    fetch: https://helix-norddal-anfibiacreativa.project-helix.page/{path}
    domain: ms/posts/(2018|2019)/.*\.(md|docx)
```
When a modified item matches that regex, the extension (`md` or `docx` in that case) will be replaced by the value `source`, fetched from `helix-index-pipelines` and re-indexed.

**Comment by trieloff** [comment]
Good idea, but:

1. I find the name "domain" to be confusing when it refers not to DNS domains, but to path patterns
2. from a user experience perspective, it might be easier to go with list of [`micromatch`](https://www.npmjs.com/package/micromatch) glob expressions (we use the same in helix-cli and pipeline) than regular expressions:

```yaml
indices:
  blog-posts:
    source: html
    fetch: https://helix-norddal-anfibiacreativa.project-helix.page/{path}\
    include: 
      - ms/posts{2018..2019}/*.md
      - ms/posts{2018..2019}/*.md
```

**Comment by dominique-pfister** [comment]
Nice one, much more intuitive, agreed!

**Comment by trieloff** [comment]
That also leaves the door open to having an `exclude` property later ;)

**Comment by tripodsan** [comment]
I think there is a confusion between the paths reported by observation, and paths used for indexing:

1. the user needs to know all the sources that are relevant for rendering the page and include them as `include`.
2. the include specifies a resolved source path (although the leading '/' is missing in the example), but the `fetch` property uses a `{path}` as resource path+magic extension (eg: `/ms/posts/2019/foo`)

I don't know a better solution for (1), except maybe to separate the include/exclude more.
Further, I would make the `.html` extension more explicit. eg:

```yaml
indices:
  blog-posts:
    source: html
    fetch: https://helix-norddal-anfibiacreativa.project-helix.page/{path}.html
reindex:
  include:
      - /ms/posts{2018..2019}/*.(md|docx)
      - /ms/posts{2018..2019}/*.(md|docx)
      - /head.md
      - /header.md
      - /fooder.md
```

**Comment by trieloff** [comment]
Does the `reindex` property need a deeper indent? Otherwise I don't understand what it should mean.

**Comment by tripodsan** [comment]
I think it's weird that includes/excludes of the files that contribute to the website should be specified inside the index. it kind of feels wrong.

it's more like the include/exclude specified the patterns for the observation filter that would trigger a reindex.

**Comment by dominique-pfister** [comment]
> it's more like the include/exclude specified the patterns for the observation filter that would trigger a reindex.
But then every index (if there's more than one specified in the configuration), would trigger a re-index for a matching file?

**Comment by tripodsan** [comment]
hmm, as I said, maybe a separate file?

`helix-observation.yaml`:
```yaml
observation:
  - name: Index Blog posts
     action: reindex
     target: blog-posts
     include:
      - /ms/posts{2018..2019}/*.(md|docx)
      - /ms/posts{2018..2019}/*.(md|docx)
      - /head.md
      - /header.md
      - /fooder.md
  - name: Index Images
     action: reindex
     target: images
     include:
     - /**/*.gif
  - name: Extract Abstract
     action: /helix/helix-services/extract-abstract@v1
     include:
     - /**/.(md|docx)
```

**Comment by dominique-pfister** [comment]
So, we have either:
- a `target` property defining an index configuration name in `helix-query.yaml`
- an `action` property defining a OW action to invoke

In the latter case, I assume the action payload are the paths filtered by the `include` section. That sounds reasonable, although I'm wondering whether it should be part of `helix-index-files`: that action is currently associated with indexing in Algolia, so a purist could argue that its configuration should look like:
```
- name: Index Blog posts
  action: /helix-index/helix-services/index-files@v1
  target: blog-posts
  include:
    - /ms/posts{2018..2019}/*.(md|docx)
    - /ms/posts{2018..2019}/*.(md|docx)
    - /head.md
    - /header.md
    - /fooder.md
```

**Comment by trieloff** [comment]
@tripodsan I'd make `action` an optional array, so that you can have multiple listeners.

Also, order is probably not important, so we could think about making `observation` a map instead of an array:

```yaml
observation:
  posts:
    action: 
      - reindex
      - flush
    target: blog-posts
    include:
      - /ms/posts{2018..2019}/*.(md|docx)
      - /ms/posts{2018..2019}/*.(md|docx)
      - /head.md
      - /header.md
      - /footer.md
  images:
    action: reindex
    target: images
    include:
     - /**/*.gif
  abstract:
    action: /helix/helix-services/extract-abstract@v1
    include:
     - /**/.(md|docx)
```

**Comment by tripodsan** [comment]
> so we could think about making observation a map instead of an array:

I like the human readable `name`s.

> I'd make action an optional array, so that you can have multiple listeners.

and the action params? like `target` ?

**Comment by tripodsan** [comment]
> In the latter case, I assume the action payload are the paths filtered by the `include` section.

no, the payload to any action is the filtered changes.

**Comment by tripodsan** [comment]
so maybe:

```yaml
- name: Index Blog posts
  action: /helix-index/helix-services/index-files@v1
  params: 
     indexName: blog-posts
  include:
    - /ms/posts{2018..2019}/*.(md|docx)
    - /ms/posts{2018..2019}/*.(md|docx)
    - /head.md
    - /header.md
    - /fooder.md
```
